name: book_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18
  device_info_plus: ^8.1.0
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  outline_search_bar: ^2.3.0
  carousel_slider: ^4.2.1
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/logo_400.png"
  android: true
  ios: true
#  min_sdk_android: 21

flutter_native_splash:
  color: "#4caf50"
  icon_background_color: "#4caf50"
  image: assets/logo_864.png
  android: true
  ios: true
  android_12:
    color: "#4caf50"
    icon_background_color: "#4caf50"
    image: assets/splash_android_12.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/home/
    - assets/background/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400